export const CART_ADD_FURNITURE = "CART_ADD_FURNITURE";
export const CART_REMOVE_FURNITURE = "CART_REMOVE_FURNITURE";
export const FURNITURE_INCREASE_QTY = "FURNITURE_INCREASE_QTY";
export const FURNITURE_DECREASE_QTY = "FURNITURE_DECREASE_QTY";




