export const FURNITURE_LIST_REQUEST = "FURNITURE_LIST_REQUEST"
export const FURNITURE_LIST_SUCCESS = "FURNITURE_LIST_SUCCESS"
export const FURNITURE_LIST_FAIL = "FURNITURE_LIST_FAIL"

export const FURNITURE_DETAILS_REQUEST = "FURNITURE_DETAILS_REQUEST"
export const FURNITURE_DETAILS_SUCCESS = "FURNITURE_DETAILS_SUCCESS"
export const FURNITURE_DETAILS_FAIL = "FURNITURE_DETAILS_FAIL"

