const furniture = [
  {
    id: 1,
    name: "Trenton Modular Sofa",
    image: "/images/Trenton Modular Sofa.png",
    description:
      "The first truly easy-to-move sofa thanks to our award-winning modular design; it has plenty of room for three people, or more if you're into cuddling. It's packed with all the clever, life-changing features you expect from Burrow, starting with a built-in USB charger.",
    brand: "Burrow",
    category: "Chairs",
    price: 800,
    countInStock: 10,
    rating: 2.5,
    numReviews: 12,
  },
  {
    id: 2,
    name: "Granite Dining Table",
    image: "/images/Granite Dining Table.png",
    description:
      "Invite your family into the heart of your home with the Vail 6-piece dining set. This collection's table features a timeworn planked oak top that creates a unique two-tone contrast. The chairs have heavily woven fabric with a textured feel. As a bonus, the table features drawers to store away smaller items. This is trend-right urban collection exudes charming farmhouse style.",
    brand: "Raymour & Flanigan",
    category: "Dinning Table",
    price: 2000,
    countInStock: 10,
    rating: 0.5,
    numReviews: 12,
  },
  {
    id: 3,
    name: "Outdoor Bar Table and Stool",
    image: "/images/Outdoor Bar Table and Stool.png",
    description:
      "Enjoy your outdoor space with a cup of coffee in the morning or cocktails in the evening around the La Casa Café 5-Piece Farmhouse Trestle Bar Set. This classic set seats up to four guests for a relaxed outdoor dining experience. The La Casa Café Bar Side Chairs are contoured for comfort while the Farmhouse Trestle 37 Bar Table provides plenty of legroom underneath.",
    brand: "Polywood",
    category: "Bar",
    price: 2500,
    countInStock: 10,
    rating: 0,
    numReviews: 12,
  },
  {
    id: 4,
    name: "Plain Console",
    image: "/images/Plain Console.png",
    description:
      "This console table is just right for catching your keys as you come in the door, or showing off your accent lamps, books, and plants behind the sofa. Its engineered wood tabletop and a contrasting iron base give it an industrial-inspired mixed material look that we love. This entryway table resists staining and scratching, ideal for homes with kids and pets. Plus, with its generous 71'' length, it even works as a coffee shop-style dining table: Just add a pair of stools and an exposed brick wall.",
    brand: "Wayfair",
    category: "Console",
    price: 186,
    countInStock: 10,
    rating: 3,
    numReviews: 12,
  },
  {
    id: 5,
    name: "Grain Coffee Table",
    image: "/images/Grain Coffee Table.png",
    description:
      "The Fontaine occasional table set adds a cool modern touch to any living space. Its gray wood tone agrees with any decor you choose.",
    brand: "Raymour & Flanigan",
    category: "Sofa",
    price: 419,
    countInStock: 10,
    rating: 1,
    numReviews: 12,
  },
  {
    id: 6,
    name: "Kent Coffee Table",
    image: "/images/Kent Coffee Table.png",
    description:
      "The Kent Coffee Table is a classically designed table with a modern flair. It features a large tabletop area and mid century style wooden legs. Place this coffee table in any living room or seating area. Available in Walnut Wood.",
    brand: "Burrow",
    category: "Chairs",
    price: 520,
    countInStock: 10,
    rating: 1.5,
    numReviews: 12,
  },
  {
    id: 7,
    name: "Round Coffee Table",
    image: "/images/Round Coffee Table.png",
    description:
      "Decorate your living room with a coffee table. The eye-catching design of this coffee table features a hand-patched top and metal legs that create a bold retro American country style. Lower natural shelves provide space for displaying and storing magazines and other essentials.",
    brand: "Wayfair",
    category: "Tables",
    price: 217,
    countInStock: 10,
    rating: 3.5,
    numReviews: 12,
  },
  {
    id: 8,
    name: "Reclaimed Teak Coffee Table",
    image: "/images/Reclaimed Teak Coffee Table.png",
    description:
      "A flat natural wood top is given open, airy appeal with a rattan base, making coffee table ideal for adding engaging visual intrigue in a contemporary. Two-tiered design provide ample room for your books.",
    brand: "Burrow",
    category: "Chairs",
    price: 459,
    countInStock: 10,
    rating: 3,
    numReviews: 12,
  },
  {
    id: 9,
    name: "Plain Console",
    image: "/images/Plain Console.png",
    description:
      "Did you hear that? Of course you didn't — designed with soft-close drawers, the very understated Lenia Media Unit makes tidying up fuss-free and verrry quiet. Plus, its discreet opening for cord management keeps wires organized so you can focus on the important things on display up top. Ah the sweet sound of organization.",
    brand: "Lenia",
    category: "Tables",
    price: 899,
    countInStock: 10,
    rating: 4,
    numReviews: 12,
  },
  {
    id: 10,
    name: "Reclaimed Teak Sideboard.",
    image: "/images/Reclaimed Teak Sideboard.png",
    description:
      "Rich texture and organic spirit are conveyed through an eye-catching mixture of mango woods, cotton rope and natural cane. Iron accents adopt gunmetal finishes, refreshing forms’ iconic mid-century influence, as a clean-lined aesthetic is met with modern functionality. ",
    brand: "Burrow",
    category: "Chairs",
    price: 1299,
    countInStock: 10,
    rating: 1,
    numReviews: 12,
  },
  {
    id: 11,
    name: "Outdoor Four Chairs And Table",
    image: "/images/Outdoor Four Chairs And Table.png",
    description:
      "If Camelot was a design destination, the knights would have sat at an oval dining table. Share a meal with 4-6 of your favorite people (more if you don’t mind bumping elbows). This mid-century style walnut dining table is set atop solid wood legs and features a veneered starburst-style design on the top. Glamour and sculptural interest, all in one table.",
    brand: "Article",
    category: "Table",
    price: 700,
    countInStock: 10,
    rating: 1.5,
    numReviews: 12,
  },
  {
    id: 12,
    name: "Bella Chair And Table",
    image: "/images/Bella Chair And Table.png",
    description:
      "Our Olivia dining table is constructed from solid American oak with strong, cylindrical legs neatly aligned to the curve of the table top. The Olivia table melds a playful, casual edge into her smooth, modern, Scandinavian-inspired design. Bring the soft, warm tones and smooth, velvety texture of the Olivia Table into the heart of your home and enjoy the effortless lifestyle Olivia creates. Create your sanctuary: match your Olivia Table with the Olivia Chairs and Sofa range for easy flow. With the right care, the Olivia Table is long-lasting and will remain a fixture for years to come.",
    brand: "Icon by Design",
    category: "Tables",
    price: 800,
    countInStock: 10,
    rating: 2,
    numReviews: 12,
  },
  {
    id: 13,
    name: "Granite Square Side Table",
    image: "/images/Granite Square Side Table.png",
    description:
      "The stunning Etta Side Table features a solid design mixing black oak wood veneer, tempered glass accent on top and a brushed aluminum base. The Etta is a sophisticated marriage of simplicity and functionality. Matching coffee table, console table and TV stand also available.",
    brand: "Burrow",
    category: "Chairs",
    price: 800,
    countInStock: 10,
    rating: 2.5,
    numReviews: 12,
  },
  {
    id: 14,
    name: "Asgaard Sofa",
    image: "/images/Asgaard Sofa.png",
    description:
      "The perfect leather sofa is now in reach. Our Nomad Sofa is 86 of soft, supple, and sophisticated top-grain Italian leather, and includes all the clever, life-changing conveniences you expect from Burrow, like our modular, easy-to-move design and built-in USB charger.",
    brand: "Burrow",
    category: "Chairs",
    price: 800,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    id: 15,
    name: "Maya Sofa Three Seater",
    image: "/images/Maya Sofa Three Seater.png",
    description:
      "Sit back. Stretch out. Slow down. The Union Collection makes every form of comfort possible, from solo naps to family gatherings. It’s our biggest, deepest, plushest, widest modular seating design to date, created with movie nights, video games, and weekend cartoons in mind. But all that maximalism doesn’t minimize everything else Burrow is known for: it’s still a breeze to build, it’s made with the best materials we can get our hands on, and we ship it to your door for free. Now that’s big.",
    brand: "Burrow",
    category: "Sofas",
    price: 3595,
    countInStock: 10,
    rating: 4,
    numReviews: 12,
  },
  {
    id: 16,
    name: "Outdoor Sofa Set",
    image: "/images/Outdoor Sofa Set.png",
    description:
      "The cornerstone of our Nomad Collection is the essential sofa reinvented for modern life. The first truly easy-to-move sofa thanks to our award-winning modular design; it has plenty of room for three people, or more if you're into cuddling. It's packed with all the clever, life-changing features you expect from Burrow, starting with a built-in USB charger. ",
    brand: "Burrow",
    category: "Sofas",
    price: 800,
    countInStock: 10,
    rating: 5,
    numReviews: 12,
  },
];

export default furniture;
